### ISSUE TITLE
Add Pylons Project meta stuff

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/webob#226]
Pyramid is the example that we usually follow. I suggest the following todos:

- [x] Add a [contributing.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/). See [Pyramid's](https://github.com/Pylons/pyramid/blob/master/contributing.md)
- [x] Add a CONTRIBUTORS.txt for signing.
- [x] Verify that the license is the correct type. If not correct, then use [Pyramid's license].(https://github.com/Pylons/pyramid/blob/master/LICENSE.txt)

I volunteer to make the PR, once it is determined what, if anything, should be done.

**Comment by bertjwregeer** [comment]
WebOb uses the MIT license, and as such does not require a CONTRIBUTORS.txt file to be signed for contributions. A contributing.md may be something to add.

**Comment by stevepiercy** [comment]
See #225

**Comment by bertjwregeer** [comment]
Thanks @stevepiercy
